### ISSUE TITLE
factorymod changes (lots here)

### ISSUE THREAD

**Issue by Convoy20** [DevotedMC/Rhea-Public#7]
Add in config for evolving factories

https://docs.google.com/document/d/1v6osKg7RvQUkIEBrZnDYVw6QZGyb3b0um6QFEj_oTFw/edit

```
    production_time: 4s
    production_max: 16s
    production_min: 1s
    fuel_consumption: 2
    fuel_consumption_max: 8
    fuel_consumption_min: 1
    name: Bake Bread
    type: PRODUCTION
    input:
      wheat:
        material: WHEAT
        amount: 64
    output:
      bread:
        material: BREAD
        amount: 48
        amount_max: 92
        amount_min: 36

```

Included are the new fields for each recipe. For launch just adding in these with a reasonable variance will be good. We might add more config options as the change gets developed, but having something to work off of is good.
